config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, uniqueness: true,
            length: { minimum: 5 }

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%")
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    # to list the articles with the newest entry first (based on column 'created_at')
    if params[:search]
      @articles = Article.search(params[:search]).order("created_at DESC")
    else
      @articles = Article.order("created_at DESC")
    end

    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # ADD_COMMENT
  def add_comment
    redirect_to @article
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to articles_url
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<div class="row">
  <div class="col-sm-8">
        <div class="card">
          <div class="card-header">
            <h3><%= article.title %></h3>
          </div>
          <div class="card-block">
            <p class="card-text"><%= @markdown.render(article.body).html_safe %></p>
            <p class="card-text"><small class="text-muted">Last updated <%= article.updated_at %></small></p>
            <div align="right">
              <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-success'%>
              <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure to delete?' }, class:'btn btn-danger' %>
              <%= link_to 'Add comment', article, class:'btn btn-primary' %>
            </div>
          </div>
          <div class="card-footer">
            <h6>Comments:</h6>
            <ul class="list-group">
              <%= render article.comments %>
            </ul>
          </div>
        </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="card">
        <div class="card-block">
          <h2>Enter search title</h2>
          <%= form_tag(articles_path, :method => "get", enforce_utf8: false, class: "navbar-form", id: "search-form") do %>
              <%= label_tag(:searchLabel, "Title") %>
              <%= text_field_tag :search, params[:search]  %>
              <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>
<p id="notice"><%= notice %></p>
<div class="container">
  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<li class="list-group-item">
  <%= comment.commenter %>: <%= comment.body %>
  <br/>
  <small>(Last updated <%= comment.updated_at %>)</small>
  <%= link_to 'Delete', [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure to delete this comment?' },
              class: 'btn btn-danger btn-sm'
  %>
</li>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thien's blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <nav class="navbar navbar-light bg-faded" id="main_navs">
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/articles">Articles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/articles/new">New article</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/">About</a>
      </li>
    </ul>

  </nav>

  <%= yield %>

  <footer class="navbar navbar-light bg-faded">
    <div class="container" align="middle">
      <p class="text-muted">Designed and built with all the love in the world by @thienleminh1982 :-)
        <br/>
        <a class="nav-link" href="https://github.com/thienleminh1982">thienleminh1982 on GitHub</a>
      </p>
    </div>
  </footer>

</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container" align="middle">
  <h1>Welcome to my Rails blog app !!!</h1>
  <h3>This is my first RoR applications for CoderSchool</h3>
  <img src="http://www.mediazo.com/new/wp-content/uploads/2013/09/Blogging-communities.jpg" height="363" width="544" />
  <br/><br/>
</div>